# Generated by Django 4.1.3 on 2022-11-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CiudadResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigoPostal', models.IntegerField(verbose_name='Codigo Postal')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.IntegerField(null=True)),
                ('fecha', models.DateField(null=True, verbose_name='Fecha MM/DD/AAAA')),
                ('montoComprobante', models.FloatField(default=0, verbose_name='Monto Total')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('imagen', models.FileField(null=True, upload_to='../static/img/')),
                ('baja', models.BooleanField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo2.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_m', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email_m', models.EmailField(max_length=150, null=True)),
                ('dni_m', models.IntegerField(verbose_name='DNI')),
                ('legajo_m', models.CharField(max_length=10, verbose_name='Legajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_m', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email_m', models.EmailField(max_length=150, null=True)),
                ('dni_m', models.IntegerField(verbose_name='DNI')),
                ('matricula_m', models.CharField(max_length=10, verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Numero de Socio')),
                ('fechaAsociacion', models.DateField(null=True, verbose_name='Fecha de alta en al club')),
                ('idCategoriaSocio', models.CharField(choices=[('C', 'Cadete'), ('A', 'Activo'), ('V', 'Vitalicio'), ('H', 'Honorario'), ('B', 'Baja'), ('F', 'Fallecido'), ('R', 'Renuncia')], default='A', max_length=1, verbose_name='Categoria de Socio ante el Club')),
                ('distintiva', models.CharField(max_length=6, null=True, verbose_name='Señal Distintiva')),
                ('categoriaDistintiva', models.CharField(choices=[('N', 'Novicio'), ('G', 'General'), ('S', 'Superior'), ('E', 'Especial')], default='N', max_length=1, verbose_name='Categoria de señal Distintiva')),
                ('expediente', models.FileField(null=True, upload_to='expedientes/', verbose_name='Carpeta de expedientes')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('estadoCivil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('B', 'Concubinado'), ('U', 'Union Civil'), ('V', 'Viudo')], default='S', max_length=1, verbose_name='Estado Civil')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No Binario'), ('O', 'Otros')], default='F', max_length=1, verbose_name='Sexo')),
                ('tipo_dni', models.CharField(default='DNI', max_length=10, verbose_name='Tipo de Documento')),
                ('dni', models.IntegerField(null=True, verbose_name='Numero de Documento')),
                ('cuil', models.IntegerField(null=True, verbose_name='CUIL O CUIT')),
                ('fechaNacimient', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('ocupacion', models.CharField(max_length=100, null=True, verbose_name='Ocupacion')),
                ('telDomicilio', models.IntegerField(null=True, verbose_name='Teléfono Fijo')),
                ('telCelular', models.IntegerField(null=True, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Correo Electrónico - email')),
                ('condicionDePago', models.CharField(choices=[('S', 'En Sede'), ('C', 'Cobrador'), ('L', 'En Linea')], default='S', max_length=1, verbose_name='Condicion de Pago')),
                ('pesentadoPor', models.IntegerField(null=True, verbose_name='Fue presentado por')),
                ('venciDistintiva', models.DateField(null=True, verbose_name='Vencimiento de la Distintiva')),
                ('web', models.CharField(max_length=100, null=True, verbose_name='web')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Entrenando'), (3, 'Finalizado')], default=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo2.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo2.socio')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='socios',
            field=models.ManyToManyField(to='grupo2.socio'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.IntegerField(null=True)),
                ('montoCuota', models.FloatField(default=0, max_length=6)),
                ('baja', models.BooleanField(default=0)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo2.comprobante')),
                ('socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo2.socio')),
            ],
        ),
    ]
