# Generated by Django 4.1.3 on 2022-11-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadresidencia',
            name='codigoPostal',
            field=models.CharField(max_length=8, verbose_name='Codigo Postal'),
        ),
    ]
