# Generated by Django 4.1.3 on 2022-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0003_socio_ciudadresidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='comprobante',
            field=models.CharField(max_length=6, null=True, verbose_name='Numero de Comprobante'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='cuota',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
