# Generated by Django 4.1.3 on 2022-11-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0004_vitalicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_m', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email_m', models.EmailField(max_length=150, null=True)),
                ('dni_m', models.IntegerField(verbose_name='DNI')),
                ('legajo_m', models.CharField(max_length=10, verbose_name='Legajo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_m', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email_m', models.EmailField(max_length=150, null=True)),
                ('dni_m', models.IntegerField(verbose_name='DNI')),
                ('matricula_m', models.CharField(max_length=10, verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
