# Generated by Django 4.1.4 on 2022-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0005_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.FileField(null=True, upload_to='expediente/', verbose_name='Imagen a mostrar'),
        ),
    ]
