# Generated by Django 4.1.3 on 2022-11-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0005_docentem_estudiantem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudadResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCiudad', models.IntegerField(max_length=3)),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigoPostal', models.IntegerField(max_length=4, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='comprobante',
            fields=[
                ('comprobante', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('montoComprobante', models.FloatField(default=0, max_length=6)),
                ('observaciones', models.CharField(max_length=100, null=True, verbose_name='Observacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='socio',
            name='id',
        ),
        migrations.AddField(
            model_name='socio',
            name='categoriaDistintiva',
            field=models.CharField(choices=[('N', 'Novicio'), ('G', 'General'), ('S', 'Superior'), ('E', 'Especial')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='socio',
            name='condicionDePago',
            field=models.CharField(choices=[('S', 'En Sede'), ('C', 'Cobrador'), ('L', 'En Linea')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='socio',
            name='cuil',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='socio',
            name='distintiva',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='estadoCivil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('B', 'Concubinado'), ('U', 'Union Civil'), ('V', 'Viudo')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='socio',
            name='expediente',
            field=models.FileField(null=True, upload_to='expedientes/'),
        ),
        migrations.AddField(
            model_name='socio',
            name='fechaAsociacion',
            field=models.DateField(null=True, verbose_name='Fecha de alta en al club'),
        ),
        migrations.AddField(
            model_name='socio',
            name='fechaNacimient',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='socio',
            name='idCategoriaSocio',
            field=models.CharField(choices=[('C', 'Cadete'), ('A', 'Activo'), ('V', 'Vitalicio'), ('H', 'Honorario'), ('B', 'Baja'), ('F', 'Fallecido'), ('R', 'Renuncia')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='socio',
            name='idSocio',
            field=models.IntegerField(default=0, max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='socio',
            name='ocupacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Ocupacion'),
        ),
        migrations.AddField(
            model_name='socio',
            name='pesentadoPor',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No Binario'), ('O', 'Otros')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='socio',
            name='telCelular',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='telDomicilio',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='venciDistintiva',
            field=models.DateField(null=True, verbose_name='Vencimiento de la Distintiva'),
        ),
        migrations.AddField(
            model_name='socio',
            name='web',
            field=models.CharField(max_length=100, null=True, verbose_name='web'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.IntegerField(null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='tipo_dni',
            field=models.CharField(default='DNI', max_length=10),
        ),
        migrations.CreateModel(
            name='cuota',
            fields=[
                ('cuota', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('montoCuota', models.FloatField(default=0, max_length=6)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo2.comprobante')),
                ('socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo2.socio')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='ciudadResidencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo2.ciudadresidencia'),
        ),
    ]
