# Generated by Django 4.1.3 on 2022-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0006_ciudadresidencia_comprobante_remove_socio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.FileField(null=True, upload_to='../static/img/'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='montoComprobante',
            field=models.FloatField(default=0, max_length=6, verbose_name='Monto Total'),
        ),
    ]
