# Generated by Django 3.2.14 on 2022-12-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo2', '0007_rename_estudiante_inscripcion_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo2.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Entrenando'), (3, 'Finalizado')], default=1, verbose_name='Estado de la Inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo2.socio', verbose_name='Socio'),
        ),
    ]
